# change the prefix from 'C-b' to 'C-a'
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set defualt editor as neovim
set-option -gs editor nv

# set max lines stored in window history
set-option -g history-limit 102400

# renumber open windows after closing one
set-option -g renumber-windows on

# start with window 1
set-option -g base-index 1
# start with pane 1
set-option -gw pane-base-index 1

# split panes using | and -, make sure they open in the same path
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

unbind-key '"'
unbind-key %

# reload config file
bind-key r source-file ~/.tmux.conf

# mouse control (clickable windows, panes, resizable panes)
set-option -g mouse on

# Use Alt-arrow keys without prefix key to switch panes
bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D

# enable vi mode keys
set-option -gw mode-keys vi

unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

# allow focus events to get through to applications running in tmux
set-option -g focus-events on

### DECOR

set-option -g status-interval 5
set-option -g status-left '#{?client_prefix,#[bg=red][ #S ],#[bg=green][ #S ]}'
set-option -g status-right '[ #{user}@#H ] [ %H:%M %d-%b-%y %z ]'
set-option -g status-right-length 50

set-option -gw window-status-format ' #I:#W#F '
set-option -gw window-status-current-style 'fg=green bg=black'
set-option -gw window-status-bell-style 'bg=red'
set-option -gw window-status-separator ''

set-option -g visual-activity on
set-option -g visual-bell on
set-option -g visual-silence off
set-option -g bell-action none
set-option -gw monitor-activity off

